### ISSUE TITLE
Discussion: Moving to an Organization?

### ISSUE THREAD

**Issue by ryonakano** [elework/Spreadsheet#93]
@elegaanz Although almost 2 years has passed since you transferred the ownership to me and I've still not been able to publish the app to AppCenter yet (I eager to do this though), I wonder we may want to move to an Organization.

Since you made the elementary structure of this app I think you should also been credited (more than me :1st_place_medal:). However, with the current repository name (`ryonakano/Spreadsheet`) and the exec name (`com.github.ryonakano.spreadsheet`), users may not notice your hard work (the exec name seems to need to match the repository name in case insensitive, so it's not possible to change only the exec name to other one, and vice versa).

What do you think?

**Comment by elegaanz** [comment]
Do as you want, it is not a problem for me if I am not "credited", and you contributed a lot to the code too, so having your name in the exec name seems right to me. So, yes, if you feel like making an organization, go ahead, but it isn't extremely important to me.

**Comment by ryonakano** [comment]
Thank you, I transferred this repository to a new Organization and invited you to it.
